updater_sample: tools: import AbOtaPropertyFiles from ota_utils
Commit [1] moved the AbOtaPropertyFiles class from the ota_from_target_files
file to the ota_utils file.

Because of this move, running gen_update_config.py breaks:
AttributeError: module 'ota_from_target_files' has no attribute 'AbOtaPropertyFiles'

Fix the error by importing from ota_utils instead of from
ota_from_target_files.

[1] https://android-review.googlesource.com/c/platform/build/+/2201755
Change-Id: Ife3d26bdfdeedf26888cd311ed490edf73c103da
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>